import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Inter, JetBrains_Mono } from "next/font/google";
import Navbar from "@/components/custom/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-heading",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        inter.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className=" py-3 px-3 md:px-6 ">{children}</div>
      </body>
    </html>
  );
}
